"""
Comprehensive Government of India Agricultural Commodity & Mandi Master Catalog.
Sourced from:
- Ministry of Agriculture & Farmers Welfare (Agmarknet DMI Faridabad)
- Directorate of Economics & Statistics (DES) / Commission for Agricultural Costs & Prices (CACP)
- Data.gov.in Resource IDs: 9ef84268-d588-465a-a308-a864a43d0070 & 35985678-0d79-46b4-9ed6-6f13308a1d24
"""

from datetime import datetime

TODAY_STR = datetime.now().strftime("%d/%m/%Y")

MASTER_GOVT_AGRICULTURAL_PRICES = [
    # ==========================================
    # 1. VEGETABLES (SOLANACEOUS, ALLIUMS, LEAFY, CRUCIFERS, CUCURBITS, ROOTS, PODS, TUBERS)
    # ==========================================
    {
        "commodity": "Tomato",
        "variety": "Hybrid Vine",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Vijayawada Rythu Bazar / APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 22.0,
        "max_price_kg": 28.0,
        "modal_price_kg": 25.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Tomato",
        "variety": "Local / Desi Native",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Gannavaram Rythu Bazar",
        "arrival_date": TODAY_STR,
        "min_price_kg": 18.0,
        "max_price_kg": 24.0,
        "modal_price_kg": 21.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Tomato",
        "variety": "Roma / Salad Oval",
        "grade": "Super Grade",
        "state": "Karnataka",
        "district": "Kolar",
        "market": "Kolar APMC Mandi (Asia's 2nd Largest Tomato Market)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 24.0,
        "max_price_kg": 32.0,
        "modal_price_kg": 28.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Onion",
        "variety": "Kurnool Rose / Red Medium",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Kurnool",
        "market": "Kurnool APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 28.0,
        "max_price_kg": 36.0,
        "modal_price_kg": 32.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Onion",
        "variety": "Nashik Red Premium",
        "grade": "Super Grade",
        "state": "Maharashtra",
        "district": "Nashik",
        "market": "Lasalgaon APMC Mandi (Asia's Largest Onion Market)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 30.0,
        "max_price_kg": 38.0,
        "modal_price_kg": 34.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Onion",
        "variety": "White Onion (Dehydration Grade)",
        "grade": "FAQ",
        "state": "Gujarat",
        "district": "Bhavnagar",
        "market": "Mahuva APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 25.0,
        "max_price_kg": 33.0,
        "modal_price_kg": 29.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Potato",
        "variety": "Jyoti / Local White",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Vijayawada Wholesale APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 22.0,
        "max_price_kg": 30.0,
        "modal_price_kg": 26.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Potato",
        "variety": "Kufri Bahar / Chipsona",
        "grade": "Super Grade",
        "state": "Uttar Pradesh",
        "district": "Agra",
        "market": "Agra Wholesale APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 18.0,
        "max_price_kg": 25.0,
        "modal_price_kg": 21.5,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Green Chilli",
        "variety": "Guntur Hot / Teja",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "market": "Guntur Mirchi Yard / APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 55.0,
        "max_price_kg": 75.0,
        "modal_price_kg": 65.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Green Chilli",
        "variety": "Jwala Thin Spicy",
        "grade": "FAQ",
        "state": "Telangana",
        "district": "Khammam",
        "market": "Khammam APMC Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 50.0,
        "max_price_kg": 68.0,
        "modal_price_kg": 58.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Brinjal (Eggplant / Baingan)",
        "variety": "Native Purple Round",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Gannavaram Rythu Bazar",
        "arrival_date": TODAY_STR,
        "min_price_kg": 18.0,
        "max_price_kg": 26.0,
        "modal_price_kg": 22.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Brinjal (Eggplant / Baingan)",
        "variety": "Green Striped Long",
        "grade": "FAQ",
        "state": "Karnataka",
        "district": "Bangalore Rural",
        "market": "Doddaballapur APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 20.0,
        "max_price_kg": 28.0,
        "modal_price_kg": 24.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Lady's Finger (Bhindi / Okra)",
        "variety": "Hybrid Green Tender",
        "grade": "FAQ",
        "state": "Telangana",
        "district": "Warangal",
        "market": "Warangal APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 32.0,
        "max_price_kg": 44.0,
        "modal_price_kg": 38.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Spinach (Palak)",
        "variety": "Organic Native Leafy",
        "grade": "Fresh Harvest",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Benz Circle Rythu Bazar",
        "arrival_date": TODAY_STR,
        "min_price_kg": 14.0,
        "max_price_kg": 22.0,
        "modal_price_kg": 18.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "AP Rythu Bazar / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Coriander Leaves (Dhania Patta)",
        "variety": "Native Aromatic",
        "grade": "Fresh Bunch",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Vijayawada Rythu Bazar",
        "arrival_date": TODAY_STR,
        "min_price_kg": 25.0,
        "max_price_kg": 45.0,
        "modal_price_kg": 35.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Mint Leaves (Pudina)",
        "variety": "Spearmint Green",
        "grade": "Fresh Harvest",
        "state": "Telangana",
        "district": "Hyderabad",
        "market": "Bowenpally APMC Agricultural Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 20.0,
        "max_price_kg": 35.0,
        "modal_price_kg": 28.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Fenugreek Leaves (Methi)",
        "variety": "Kasuri Small Leaf",
        "grade": "Fresh Bunch",
        "state": "Maharashtra",
        "district": "Pune",
        "market": "Gultekdi Pune APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 22.0,
        "max_price_kg": 36.0,
        "modal_price_kg": 30.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Curry Leaves (Kadi Patta)",
        "variety": "Native Dark Green",
        "grade": "Fresh Harvest",
        "state": "Tamil Nadu",
        "district": "Coimbatore",
        "market": "Mettupalayam APMC Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 28.0,
        "max_price_kg": 42.0,
        "modal_price_kg": 35.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Cabbage",
        "variety": "Golden Acre Round",
        "grade": "FAQ",
        "state": "Karnataka",
        "district": "Belagavi",
        "market": "Belagavi APMC Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 12.0,
        "max_price_kg": 18.0,
        "modal_price_kg": 15.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Cauliflower",
        "variety": "Snowball White",
        "grade": "FAQ",
        "state": "Karnataka",
        "district": "Kolar",
        "market": "Kolar APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 20.0,
        "max_price_kg": 30.0,
        "modal_price_kg": 25.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Bottle Gourd (Lauki / Sorakaya)",
        "variety": "Long Pale Green",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Vijayawada Rythu Bazar",
        "arrival_date": TODAY_STR,
        "min_price_kg": 16.0,
        "max_price_kg": 24.0,
        "modal_price_kg": 20.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Bitter Gourd (Karela / Kakarakaya)",
        "variety": "Dark Green Spiny",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "market": "Tenali Rythu Bazar",
        "arrival_date": TODAY_STR,
        "min_price_kg": 28.0,
        "max_price_kg": 42.0,
        "modal_price_kg": 35.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Ridge Gourd (Turai / Beerakaya)",
        "variety": "Ribbed Tender Green",
        "grade": "FAQ",
        "state": "Telangana",
        "district": "Rangareddy",
        "market": "Gaddi Annaram APMC Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 30.0,
        "max_price_kg": 45.0,
        "modal_price_kg": 38.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Snake Gourd (Potlakaya / Chichinda)",
        "variety": "Long Striped Green",
        "grade": "FAQ",
        "state": "Tamil Nadu",
        "district": "Madurai",
        "market": "Madurai Paravai APMC Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 22.0,
        "max_price_kg": 34.0,
        "modal_price_kg": 28.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Ivy Gourd (Tindora / Dondakaya)",
        "variety": "Small Striped Tender",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Gannavaram Rythu Bazar",
        "arrival_date": TODAY_STR,
        "min_price_kg": 25.0,
        "max_price_kg": 38.0,
        "modal_price_kg": 32.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Ash Gourd (Petha / Boodidha Gummadi)",
        "variety": "Wax Gourd Large",
        "grade": "FAQ",
        "state": "Kerala",
        "district": "Palakkad",
        "market": "Palakkad Wholesale APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 15.0,
        "max_price_kg": 22.0,
        "modal_price_kg": 18.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Pumpkin (Kaddu / Gummadikaya)",
        "variety": "Yellow Flesh Sweet",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "market": "Guntur APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 12.0,
        "max_price_kg": 18.0,
        "modal_price_kg": 15.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Cucumber (Kheera / Dosakaya)",
        "variety": "Green Salad Crunchy",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Benz Circle Rythu Bazar",
        "arrival_date": TODAY_STR,
        "min_price_kg": 15.0,
        "max_price_kg": 24.0,
        "modal_price_kg": 20.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Carrot (Gajar)",
        "variety": "Orange Native Tender",
        "grade": "Super Grade",
        "state": "Tamil Nadu",
        "district": "Nilgiris",
        "market": "Ooty APMC Market Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 35.0,
        "max_price_kg": 48.0,
        "modal_price_kg": 42.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Radish (Mooli / Mullangi)",
        "variety": "White Japanese Long",
        "grade": "FAQ",
        "state": "Punjab",
        "district": "Amritsar",
        "market": "Amritsar Bhagtanwala APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 14.0,
        "max_price_kg": 22.0,
        "modal_price_kg": 18.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Beetroot",
        "variety": "Dark Red Crimson Globe",
        "grade": "Super Grade",
        "state": "Karnataka",
        "district": "Hassan",
        "market": "Hassan APMC Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 22.0,
        "max_price_kg": 32.0,
        "modal_price_kg": 27.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Sweet Potato (Shakarkand / Chilakada Dumpa)",
        "variety": "Red Skin White Flesh",
        "grade": "FAQ",
        "state": "Odisha",
        "district": "Cuttack",
        "market": "Cuttack Malgodown APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 24.0,
        "max_price_kg": 35.0,
        "modal_price_kg": 30.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Capsicum (Bell Pepper / Shimla Mirch)",
        "variety": "Green Bell Crunchy",
        "grade": "Super Grade",
        "state": "Karnataka",
        "district": "Bangalore",
        "market": "Binny Mill APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 38.0,
        "max_price_kg": 55.0,
        "modal_price_kg": 46.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Capsicum (Bell Pepper)",
        "variety": "Polyhouse Red & Yellow",
        "grade": "Exotic Premium",
        "state": "Maharashtra",
        "district": "Pune",
        "market": "Narayangaon APMC Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 90.0,
        "max_price_kg": 140.0,
        "modal_price_kg": 115.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Cluster Beans (Gawar / Goruchikkudu)",
        "variety": "Native Tender Green",
        "grade": "FAQ",
        "state": "Rajasthan",
        "district": "Bikaner",
        "market": "Bikaner APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 32.0,
        "max_price_kg": 48.0,
        "modal_price_kg": 40.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "French Beans (Farasbi)",
        "variety": "Bush Stringless",
        "grade": "Super Grade",
        "state": "Karnataka",
        "district": "Chikkaballapur",
        "market": "Chikkaballapur APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 40.0,
        "max_price_kg": 60.0,
        "modal_price_kg": 50.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Green Peas (Matar / Batani)",
        "variety": "Sweet Pod Fresh",
        "grade": "Super Grade",
        "state": "Madhya Pradesh",
        "district": "Jabalpur",
        "market": "Jabalpur APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 45.0,
        "max_price_kg": 65.0,
        "modal_price_kg": 55.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Drumstick (Moringa / Munagakaya)",
        "variety": "PKM-1 Long Pod",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "market": "Guntur APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 40.0,
        "max_price_kg": 55.0,
        "modal_price_kg": 48.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Ginger (Adrak / Allam)",
        "variety": "Raw Native Root",
        "grade": "FAQ",
        "state": "Kerala",
        "district": "Wayanad",
        "market": "Wayanad APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 80.0,
        "max_price_kg": 110.0,
        "modal_price_kg": 95.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Garlic (Lahsun / Vellulli)",
        "variety": "Medium White Clove",
        "grade": "FAQ",
        "state": "Madhya Pradesh",
        "district": "Mandsaur",
        "market": "Mandsaur APMC Mandi (Major Garlic Hub)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 120.0,
        "max_price_kg": 160.0,
        "modal_price_kg": 140.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Elephant Foot Yam (Suran / Kanda)",
        "variety": "Gajendra High Yield",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "West Godavari",
        "market": "Tadepalligudem APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 26.0,
        "max_price_kg": 36.0,
        "modal_price_kg": 31.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Colocasia (Arbi / Chamagadda)",
        "variety": "Native Brown Corms",
        "grade": "FAQ",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "market": "Varanasi Wholesale APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 28.0,
        "max_price_kg": 40.0,
        "modal_price_kg": 34.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },

    # ==========================================
    # 2. FRUITS (TROPICAL, CITRUS, SUBTROPICAL, STONE, POME & EXOTIC)
    # ==========================================
    {
        "commodity": "Banana",
        "variety": "Robusta / Grand Naine",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "East Godavari",
        "market": "Ravulapalem Banana Market Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 18.0,
        "max_price_kg": 26.0,
        "modal_price_kg": 22.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Banana",
        "variety": "Yelakki / Dwarf Cavendish",
        "grade": "Super Grade",
        "state": "Karnataka",
        "district": "Bangalore",
        "market": "Yeshwanthpur APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 38.0,
        "max_price_kg": 52.0,
        "modal_price_kg": 45.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Banana",
        "variety": "Nendran (Kerala Culinary)",
        "grade": "Super Grade",
        "state": "Kerala",
        "district": "Thrissur",
        "market": "Thrissur APMC Fruit Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 42.0,
        "max_price_kg": 58.0,
        "modal_price_kg": 50.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Mango",
        "variety": "Banganapalli / Benishan",
        "grade": "Super Grade",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Nuzvid Fruit APMC Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 65.0,
        "max_price_kg": 95.0,
        "modal_price_kg": 80.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Mango",
        "variety": "Alphonso (Hapus)",
        "grade": "Exotic Premium",
        "state": "Maharashtra",
        "district": "Ratnagiri",
        "market": "Vashi APMC Fruit Market (Navi Mumbai)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 150.0,
        "max_price_kg": 240.0,
        "modal_price_kg": 190.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Mango",
        "variety": "Totapuri (Processing Grade)",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Chittoor",
        "market": "Chittoor Mango Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 25.0,
        "max_price_kg": 36.0,
        "modal_price_kg": 30.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Papaya",
        "variety": "Red Lady 786",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Anantapur",
        "market": "Anantapur APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 16.0,
        "max_price_kg": 24.0,
        "modal_price_kg": 20.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Guava (Amrood / Jama)",
        "variety": "Allahabad Safeda / Taiwan Pink",
        "grade": "Super Grade",
        "state": "Uttar Pradesh",
        "district": "Prayagraj (Allahabad)",
        "market": "Allahabad APMC Fruit Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 35.0,
        "max_price_kg": 55.0,
        "modal_price_kg": 45.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Sweet Lime (Mosambi / Battayi)",
        "variety": "Satgudi Juicy",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Kadapa",
        "market": "Pulivendula Citrus Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 30.0,
        "max_price_kg": 45.0,
        "modal_price_kg": 38.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Lemon (Nimbu / Nimmakaya)",
        "variety": "Kagzi Round Juicy",
        "grade": "Super Grade",
        "state": "Andhra Pradesh",
        "district": "Nellore",
        "market": "Gudur Lemon APMC Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 45.0,
        "max_price_kg": 75.0,
        "modal_price_kg": 60.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Orange (Santra)",
        "variety": "Nagpur Mandarin",
        "grade": "Super Grade",
        "state": "Maharashtra",
        "district": "Nagpur",
        "market": "Nagpur Cotton Market APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 40.0,
        "max_price_kg": 65.0,
        "modal_price_kg": 52.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Pomegranate (Anar / Danimma)",
        "variety": "Bhagwa Deep Red",
        "grade": "Super Grade",
        "state": "Maharashtra",
        "district": "Solapur",
        "market": "Solapur APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 90.0,
        "max_price_kg": 140.0,
        "modal_price_kg": 115.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Watermelon (Tarbooj / Puchakaya)",
        "variety": "Sugar Baby Black",
        "grade": "FAQ",
        "state": "Telangana",
        "district": "Khammam",
        "market": "Khammam APMC Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 10.0,
        "max_price_kg": 16.0,
        "modal_price_kg": 13.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Muskmelon (Kharbuja)",
        "variety": "Honey Dew Striped",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Anantapur",
        "market": "Tadipatri APMC Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 18.0,
        "max_price_kg": 28.0,
        "modal_price_kg": 23.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Apple (Seb)",
        "variety": "Royal Delicious Shimla",
        "grade": "Super Grade",
        "state": "Himachal Pradesh",
        "district": "Shimla",
        "market": "Dhalli Shimla APMC Fruit Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 90.0,
        "max_price_kg": 150.0,
        "modal_price_kg": 120.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Grapes (Angoor / Draksha)",
        "variety": "Thompson Seedless Green",
        "grade": "Export Grade",
        "state": "Maharashtra",
        "district": "Nashik",
        "market": "Pimpalgaon APMC Grape Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 60.0,
        "max_price_kg": 95.0,
        "modal_price_kg": 78.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Pineapple (Ananas)",
        "variety": "Queen / Mauritius Giant",
        "grade": "Super Grade",
        "state": "Kerala",
        "district": "Ernakulam",
        "market": "Vazhakulam Pineapple Market (Pineapple City)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 35.0,
        "max_price_kg": 50.0,
        "modal_price_kg": 42.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Sapota (Chiku / Sapota)",
        "variety": "Cricket Ball Round",
        "grade": "FAQ",
        "state": "Gujarat",
        "district": "Navsari",
        "market": "Navsari APMC Fruit Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 25.0,
        "max_price_kg": 38.0,
        "modal_price_kg": 32.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Custard Apple (Seethaphal / Sharifa)",
        "variety": "Balanagar Native",
        "grade": "Super Grade",
        "state": "Telangana",
        "district": "Mahbubnagar",
        "market": "Mahbubnagar APMC Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 45.0,
        "max_price_kg": 75.0,
        "modal_price_kg": 60.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Coconut",
        "variety": "Raw Green Tender",
        "grade": "Large Nut",
        "state": "Andhra Pradesh",
        "district": "East Godavari",
        "market": "Ambajipeta Coconut APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 25.0,
        "max_price_kg": 35.0,
        "modal_price_kg": 30.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Coconut Development Board / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Copra (Dry Coconut / Kobbari)",
        "variety": "Milling Copra",
        "grade": "FAQ",
        "state": "Kerala",
        "district": "Kozhikode",
        "market": "Kozhikode Wholesale Copra Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 111.6,
        "max_price_kg": 122.0,
        "modal_price_kg": 111.6,
        "msp_applicable": True,
        "msp_rate_kg": 111.6,  # Central MSP ₹11,160/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Copra (Ball Copra)",
        "variety": "Edible Ball",
        "grade": "Super Grade",
        "state": "Karnataka",
        "district": "Tumkur",
        "market": "Tiptur APMC Market (Ball Copra Capital)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 120.0,
        "max_price_kg": 135.0,
        "modal_price_kg": 120.0,
        "msp_applicable": True,
        "msp_rate_kg": 120.0,  # Central MSP ₹12,000/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },

    # ==========================================
    # 3. GRAINS, CEREALS & MILLETS (ALL CCEA MSP FIXED RATES)
    # ==========================================
    {
        "commodity": "Paddy (Dhan)",
        "variety": "Common Grade (Kharif)",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Krishna",
        "market": "Civil Supplies Procurement Hub",
        "arrival_date": TODAY_STR,
        "min_price_kg": 23.0,
        "max_price_kg": 25.5,
        "modal_price_kg": 23.0,
        "msp_applicable": True,
        "msp_rate_kg": 23.0,  # Official CCEA MSP ₹2,300/quintal
        "govt_agency": "Central Govt CCEA / FCI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Paddy (Dhan)",
        "variety": "Grade 'A' Premium",
        "grade": "Super Grade",
        "state": "Telangana",
        "district": "Nizamabad",
        "market": "Nizamabad APMC Procurement Centre",
        "arrival_date": TODAY_STR,
        "min_price_kg": 23.2,
        "max_price_kg": 26.0,
        "modal_price_kg": 23.2,
        "msp_applicable": True,
        "msp_rate_kg": 23.2,  # Official CCEA MSP ₹2,320/quintal
        "govt_agency": "Central Govt CCEA / FCI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Basmati Rice (Dhan)",
        "variety": "Pusa 1121 / 1509 Aromatic",
        "grade": "Export Grade",
        "state": "Haryana",
        "district": "Karnal",
        "market": "Karnal Grain Mandi (Basmati Bowl)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 38.0,
        "max_price_kg": 46.0,
        "modal_price_kg": 42.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Wheat (Gehun)",
        "variety": "Sharbati / PBW-502 (Rabi)",
        "grade": "FAQ",
        "state": "Punjab",
        "district": "Ludhiana",
        "market": "Khanna APMC Grain Mandi (Asia's Largest Grain Market)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 22.75,
        "max_price_kg": 26.0,
        "modal_price_kg": 22.75,
        "msp_applicable": True,
        "msp_rate_kg": 22.75,  # Official CCEA MSP ₹2,275/quintal
        "govt_agency": "Central Govt CCEA / FCI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Wheat (Gehun)",
        "variety": "Durum / Malavraj (Pasta Wheat)",
        "grade": "Super Grade",
        "state": "Madhya Pradesh",
        "district": "Sehore",
        "market": "Sehore APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 25.0,
        "max_price_kg": 32.0,
        "modal_price_kg": 28.5,
        "msp_applicable": True,
        "msp_rate_kg": 22.75,
        "govt_agency": "Central Govt CCEA / FCI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Maize (Makka / Corn)",
        "variety": "Yellow Hybrid Feed",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "market": "AP Markfed Centre",
        "arrival_date": TODAY_STR,
        "min_price_kg": 22.25,
        "max_price_kg": 24.5,
        "modal_price_kg": 22.25,
        "msp_applicable": True,
        "msp_rate_kg": 22.25,  # Official MSP ₹2,225/quintal
        "govt_agency": "Central Govt CCEA / Markfed",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Jowar (Sorghum / Jonnalu)",
        "variety": "Hybrid White",
        "grade": "FAQ",
        "state": "Maharashtra",
        "district": "Solapur",
        "market": "Baramati APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 31.8,
        "max_price_kg": 35.0,
        "modal_price_kg": 31.8,
        "msp_applicable": True,
        "msp_rate_kg": 31.8,  # Official MSP ₹3,180/quintal
        "govt_agency": "Central Govt CCEA",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Jowar (Sorghum)",
        "variety": "Maldandi Premium",
        "grade": "Super Grade",
        "state": "Karnataka",
        "district": "Vijayapura (Bijapur)",
        "market": "Bijapur APMC Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 32.25,
        "max_price_kg": 38.0,
        "modal_price_kg": 32.25,
        "msp_applicable": True,
        "msp_rate_kg": 32.25,  # Official MSP ₹3,225/quintal
        "govt_agency": "Central Govt CCEA",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Bajra (Pearl Millet / Sajjalu)",
        "variety": "Hybrid Grain",
        "grade": "FAQ",
        "state": "Rajasthan",
        "district": "Jaipur",
        "market": "Chomu APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 26.25,
        "max_price_kg": 29.0,
        "modal_price_kg": 26.25,
        "msp_applicable": True,
        "msp_rate_kg": 26.25,  # Official MSP ₹2,625/quintal
        "govt_agency": "Central Govt CCEA",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Ragi (Finger Millet / Ragulu)",
        "variety": "Native Organic Brown",
        "grade": "FAQ",
        "state": "Karnataka",
        "district": "Mandya",
        "market": "Mandya APMC Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 42.9,
        "max_price_kg": 46.0,
        "modal_price_kg": 42.9,
        "msp_applicable": True,
        "msp_rate_kg": 42.9,  # Official MSP ₹4,290/quintal
        "govt_agency": "Central Govt CCEA",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Barley (Jau)",
        "variety": "Malt Grade / Feed",
        "grade": "FAQ",
        "state": "Rajasthan",
        "district": "Sri Ganganagar",
        "market": "Sri Ganganagar Grain APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 18.5,
        "max_price_kg": 21.0,
        "modal_price_kg": 18.5,
        "msp_applicable": True,
        "msp_rate_kg": 18.5,  # Official MSP ₹1,850/quintal
        "govt_agency": "Central Govt CCEA",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Foxtail Millet (Kangni / Korralu)",
        "variety": "Organic Unpolished",
        "grade": "Super Grade",
        "state": "Andhra Pradesh",
        "district": "Kurnool",
        "market": "Kurnool Millet Hub",
        "arrival_date": TODAY_STR,
        "min_price_kg": 48.0,
        "max_price_kg": 62.0,
        "modal_price_kg": 54.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Shree Anna Mission / AP Markfed",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },

    # ==========================================
    # 4. PULSES & LEGUMES (ALL CENTRAL CCEA MSP APPLICABLE)
    # ==========================================
    {
        "commodity": "Bengal Gram (Chana / Chickpea / Senagalu)",
        "variety": "Desi Brown (Rabi)",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Kurnool",
        "market": "Kurnool APMC Grain Market",
        "arrival_date": TODAY_STR,
        "min_price_kg": 54.4,
        "max_price_kg": 58.0,
        "modal_price_kg": 54.4,
        "msp_applicable": True,
        "msp_rate_kg": 54.4,  # Official MSP ₹5,440/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Kabuli Chana (Dollar Chickpea)",
        "variety": "White Bold Export",
        "grade": "Super Grade",
        "state": "Madhya Pradesh",
        "district": "Indore",
        "market": "Indore APMC Chana Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 110.0,
        "max_price_kg": 145.0,
        "modal_price_kg": 128.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Tur / Arhar Dal (Red Gram / Kandulu)",
        "variety": "Maruti White / ICPH-8",
        "grade": "FAQ",
        "state": "Karnataka",
        "district": "Kalaburagi (Gulbarga)",
        "market": "Gulbarga Dal APMC Mandi (Tur Bowl of India)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 75.5,
        "max_price_kg": 82.0,
        "modal_price_kg": 75.5,
        "msp_applicable": True,
        "msp_rate_kg": 75.5,  # Official MSP ₹7,550/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Moong (Green Gram / Pesalu)",
        "variety": "Shiny Green Bold",
        "grade": "FAQ",
        "state": "Rajasthan",
        "district": "Nagaur",
        "market": "Merta City APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 86.82,
        "max_price_kg": 92.0,
        "modal_price_kg": 86.82,
        "msp_applicable": True,
        "msp_rate_kg": 86.82,  # Official MSP ₹8,682/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Urad (Black Gram / Minumulu)",
        "variety": "T-9 Bold Black",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "market": "Guntur Grain APMC Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 74.0,
        "max_price_kg": 80.0,
        "modal_price_kg": 74.0,
        "msp_applicable": True,
        "msp_rate_kg": 74.0,  # Official MSP ₹7,400/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Masoor (Lentil / Red Dal)",
        "variety": "Small Brown Seed",
        "grade": "FAQ",
        "state": "Uttar Pradesh",
        "district": "Kanpur Nagar",
        "market": "Kanpur APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 64.25,
        "max_price_kg": 70.0,
        "modal_price_kg": 64.25,
        "msp_applicable": True,
        "msp_rate_kg": 64.25,  # Official MSP ₹6,425/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Rajma (Red Kidney Beans)",
        "variety": "Chitra / Sharmili Himalayan",
        "grade": "Super Grade",
        "state": "Jammu & Kashmir",
        "district": "Doda",
        "market": "Jammu Wholesale Grain APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 115.0,
        "max_price_kg": 160.0,
        "modal_price_kg": 135.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Agmarknet DMI",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },

    # ==========================================
    # 5. OILSEEDS (ALL CENTRAL CCEA MSP APPLICABLE)
    # ==========================================
    {
        "commodity": "Groundnut (Peanut / Verusenaga)",
        "variety": "Bold Pods In-Shell",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Anantapur",
        "market": "Anantapur Oilseed APMC (Groundnut Capital)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 67.83,
        "max_price_kg": 73.0,
        "modal_price_kg": 67.83,
        "msp_applicable": True,
        "msp_rate_kg": 67.83,  # Official MSP ₹6,783/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Soybean",
        "variety": "Yellow JS-335 (Kharif)",
        "grade": "FAQ",
        "state": "Madhya Pradesh",
        "district": "Indore",
        "market": "Indore APMC Mandi (Soybean Capital of India)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 48.92,
        "max_price_kg": 52.5,
        "modal_price_kg": 48.92,
        "msp_applicable": True,
        "msp_rate_kg": 48.92,  # Official MSP ₹4,892/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Mustard Seeds (Sarson / Rai / Avalu)",
        "variety": "Pusa Bold Black",
        "grade": "FAQ",
        "state": "Rajasthan",
        "district": "Bharatpur",
        "market": "Bharatpur APMC Mandi (Mustard Hub)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 56.5,
        "max_price_kg": 62.0,
        "modal_price_kg": 56.5,
        "msp_applicable": True,
        "msp_rate_kg": 56.5,  # Official MSP ₹5,650/quintal
        "govt_agency": "Central Govt CCEA / HAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Sunflower Seeds (Sooryakanthi)",
        "variety": "Hybrid Black Oilseed",
        "grade": "FAQ",
        "state": "Karnataka",
        "district": "Koppal",
        "market": "Koppal APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 72.8,
        "max_price_kg": 78.0,
        "modal_price_kg": 72.8,
        "msp_applicable": True,
        "msp_rate_kg": 72.8,  # Official MSP ₹7,280/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Sesame Seeds (Til / Nuvvulu)",
        "variety": "White Cleaned (Kharif)",
        "grade": "Super Grade",
        "state": "Gujarat",
        "district": "Rajkot",
        "market": "Rajkot APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 92.67,
        "max_price_kg": 105.0,
        "modal_price_kg": 92.67,
        "msp_applicable": True,
        "msp_rate_kg": 92.67,  # Official MSP ₹9,267/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Safflower (Kusuma / Kardi)",
        "variety": "Native Yellow Flower",
        "grade": "FAQ",
        "state": "Maharashtra",
        "district": "Parbhani",
        "market": "Parbhani APMC Mandi",
        "arrival_date": TODAY_STR,
        "min_price_kg": 58.0,
        "max_price_kg": 64.0,
        "modal_price_kg": 58.0,
        "msp_applicable": True,
        "msp_rate_kg": 58.0,  # Official MSP ₹5,800/quintal
        "govt_agency": "Central Govt CCEA / NAFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Nigerseed (Ramtil / Valesulu)",
        "variety": "Small Black Seed",
        "grade": "FAQ",
        "state": "Madhya Pradesh",
        "district": "Dindori",
        "market": "Dindori Tribal APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 87.17,
        "max_price_kg": 95.0,
        "modal_price_kg": 87.17,
        "msp_applicable": True,
        "msp_rate_kg": 87.17,  # Official MSP ₹8,717/quintal
        "govt_agency": "Central Govt CCEA / TRIFED",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },

    # ==========================================
    # 6. COMMERCIAL, CASH, SPICES & PLANTATION CROPS
    # ==========================================
    {
        "commodity": "Cotton (Kapas / Prathi)",
        "variety": "Medium Staple (H-4 / Shankar-6)",
        "grade": "FAQ",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "market": "CCI Procurement Centre Guntur",
        "arrival_date": TODAY_STR,
        "min_price_kg": 71.21,
        "max_price_kg": 75.0,
        "modal_price_kg": 71.21,
        "msp_applicable": True,
        "msp_rate_kg": 71.21,  # Official MSP ₹7,121/quintal
        "govt_agency": "Cotton Corporation of India (CCI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Cotton (Kapas / Prathi)",
        "variety": "Long Staple (DCH-32 / Suvin)",
        "grade": "Super Grade",
        "state": "Telangana",
        "district": "Adilabad",
        "market": "Adilabad APMC Yard (Telangana Cotton Hub)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 75.21,
        "max_price_kg": 80.0,
        "modal_price_kg": 75.21,
        "msp_applicable": True,
        "msp_rate_kg": 75.21,  # Official MSP ₹7,521/quintal
        "govt_agency": "Cotton Corporation of India (CCI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Sugarcane (Ganna / Cheraku)",
        "variety": "Co-86032 High Sugar Recovery",
        "grade": "Standard 10.25% Sugar",
        "state": "Maharashtra",
        "district": "Kolhapur",
        "market": "Cooperative Sugar Mill Gate Kolhapur",
        "arrival_date": TODAY_STR,
        "min_price_kg": 3.4,
        "max_price_kg": 3.8,
        "modal_price_kg": 3.4,
        "msp_applicable": True,
        "msp_rate_kg": 3.4,  # Central FRP ₹340/quintal
        "govt_agency": "CCEA Fair & Remunerative Price (FRP)",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Raw Jute (Pat)",
        "variety": "TD-5 Grade",
        "grade": "FAQ",
        "state": "West Bengal",
        "district": "Nadia",
        "market": "Krishnanagar Jute APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 53.35,
        "max_price_kg": 58.0,
        "modal_price_kg": 53.35,
        "msp_applicable": True,
        "msp_rate_kg": 53.35,  # Official MSP ₹5,335/quintal
        "govt_agency": "Jute Corporation of India (JCI)",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Turmeric (Haldi / Pasupu)",
        "variety": "Finger Salem / Nizamabad",
        "grade": "FAQ",
        "state": "Telangana",
        "district": "Nizamabad",
        "market": "Nizamabad Turmeric Market (Major Turmeric Hub)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 135.0,
        "max_price_kg": 170.0,
        "modal_price_kg": 150.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Spices Board of India / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Turmeric (Haldi)",
        "variety": "Erode Local Bulb",
        "grade": "Super Grade",
        "state": "Tamil Nadu",
        "district": "Erode",
        "market": "Erode Regulated Market (Turmeric City)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 140.0,
        "max_price_kg": 180.0,
        "modal_price_kg": 158.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Spices Board / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Red Chilli (Dry Mirchi / Yendu Mirapa)",
        "variety": "Teja / Deluxe Stemless",
        "grade": "Super Grade",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "market": "Guntur APMC Mirchi Yard (Asia's Largest Chilli Yard)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 180.0,
        "max_price_kg": 240.0,
        "modal_price_kg": 210.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Data.gov.in (Variety-Wise DMI)",
        "dataset_name": "Variety-wise Daily Market Prices Data of Commodity",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Red Chilli (Dry Mirchi)",
        "variety": "Byadagi Wrinkled High Color",
        "grade": "Exotic Premium",
        "state": "Karnataka",
        "district": "Haveri",
        "market": "Byadagi APMC Market Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 220.0,
        "max_price_kg": 310.0,
        "modal_price_kg": 260.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Spices Board / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Raw Tobacco (Pogaku)",
        "variety": "FCV (Flue Cured Virginia)",
        "grade": "Super Grade",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "market": "Tobacco Board Auction Platform Ongole",
        "arrival_date": TODAY_STR,
        "min_price_kg": 220.0,
        "max_price_kg": 280.0,
        "modal_price_kg": 250.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Tobacco Board of India",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Cumin Seeds (Jeera)",
        "variety": "Machine Cleaned Bold",
        "grade": "Super Grade",
        "state": "Gujarat",
        "district": "Mehsana",
        "market": "Unjha APMC Mandi (Asia's Largest Spices Market)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 260.0,
        "max_price_kg": 340.0,
        "modal_price_kg": 295.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Spices Board / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Coriander Seeds (Dhania Seeds)",
        "variety": "Eagle / Badami Green",
        "grade": "FAQ",
        "state": "Rajasthan",
        "district": "Kota",
        "market": "Ramganj Mandi (Coriander City)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 75.0,
        "max_price_kg": 95.0,
        "modal_price_kg": 85.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Spices Board / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Black Pepper (Kali Mirch / Miriyalu)",
        "variety": "Malabar Garbled MG-1",
        "grade": "Super Grade",
        "state": "Kerala",
        "district": "Idukki",
        "market": "Kochi Spices Exchange / APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 580.0,
        "max_price_kg": 680.0,
        "modal_price_kg": 630.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Spices Board of India",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Cardamom (Elaichi / Elakulu)",
        "variety": "Small Green 8mm Bold",
        "grade": "Export Grade",
        "state": "Kerala",
        "district": "Idukki",
        "market": "Bodinayakanur Cardamom Auction Centre",
        "arrival_date": TODAY_STR,
        "min_price_kg": 1850.0,
        "max_price_kg": 2400.0,
        "modal_price_kg": 2100.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Spices Board of India",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Arecanut (Supari / Vakka)",
        "variety": "Rashi / Chali Boiled",
        "grade": "Super Grade",
        "state": "Karnataka",
        "district": "Shivamogga",
        "market": "Shivamogga APMC Market Yard",
        "arrival_date": TODAY_STR,
        "min_price_kg": 460.0,
        "max_price_kg": 540.0,
        "modal_price_kg": 495.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "CAMPCO / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Cashew Nut (Kaju / Jeedipappu)",
        "variety": "Raw In-Shell W-240",
        "grade": "Super Grade",
        "state": "Andhra Pradesh",
        "district": "Srikakulam",
        "market": "Palasa Cashew Market (Cashew City)",
        "arrival_date": TODAY_STR,
        "min_price_kg": 125.0,
        "max_price_kg": 160.0,
        "modal_price_kg": 140.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "DCCI / Agmarknet",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Coffee (Kapi)",
        "variety": "Arabica Plantation 'A'",
        "grade": "Export Grade",
        "state": "Karnataka",
        "district": "Chikkamagaluru",
        "market": "Chikmagalur Coffee Curing APMC",
        "arrival_date": TODAY_STR,
        "min_price_kg": 340.0,
        "max_price_kg": 420.0,
        "modal_price_kg": 375.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Coffee Board of India",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    },
    {
        "commodity": "Tea (Chai)",
        "variety": "Nilgiri CTC Orthodox Green",
        "grade": "Super Grade",
        "state": "Tamil Nadu",
        "district": "Nilgiris",
        "market": "Coonoor Tea Auction Centre",
        "arrival_date": TODAY_STR,
        "min_price_kg": 160.0,
        "max_price_kg": 240.0,
        "modal_price_kg": 195.0,
        "msp_applicable": False,
        "msp_rate_kg": None,
        "govt_agency": "Tea Board of India",
        "dataset_name": "Current Daily Price of Various Commodities from Various Markets",
        "price_unit": "₹/kg",
        "is_live_api": False
    }
]
